global:
  title: "第%d页"
  maxRow: 30
  minRow: 3
  getOrigin: true

message:
  warning:
  - §6在取出原版末影箱时发生了一些问题
  - §6您的背包空余空间无法存放所有物品
  - §6这些无法存放的物品已经返回末影箱
  - §6请整理背包后重新上下线以取出他们
  overflow:
  - "§6请使用\"/取出溢出物品\"指令取出物品"

join_delay: 100