main: com.mengcraft.enderchest.EnderChest
name: EnderChest
version: ${project.version}

permissions:
  enderchest.default:
    description: Default permission.
    default: true
    
  enderchest.admin:
    description: Admin permission.
    default: op
    
commands:
  chest:
    description: Default command.
    permission: enderchest.admin
    uasge: /chest <name>
    
depend: [MengDB, ProtocolLib]