main: com.mengcraft.enderchest.EnderChest
name: EnderChest
version: ${project.version}

permissions:
  enderchest.default:
    description: Default permission.
    default: true
    
depend: [MengDB, ProtocolLib]