main: com.mengcraft.enderchest.Main
name: EnderChest
version: 0.2

permissions:
  enderchest.admin:
    description: Admin permission.
    default: op
    
commands:
  chest:
    description: Default command.
    permission: enderchest.admin
    uasge: /chest <name>
    
depend: [SimpleORM]